### PR TITLE
Part1

### PR DESCRIPTION
**Pull request by Bberry2016**
Slack Username: Bberry2016

### CODE REVIEW

**Review by matkatmusic — CHANGES_REQUESTED** [review]
Great, proceed to the next set of instructions in main.cpp

**Review by Bberry2016 — COMMENTED** [review]
Project 3 Part 1 Revisions

**Comment by Bberry2016** [comment]
> Great, proceed to the next set of instructions in main.cpp

**Review by Bberry2016 — COMMENTED** [review]
Part 3 Changes

**Review by matkatmusic — CHANGES_REQUESTED** [review]
Most of your function names do not match the plain-english descriptions.
These function names should match or almost match 1:1.
```
// - capture string vibrations
```
you put `readVibration` in the code.
you should have put `captureStringVibrations` in the code
This concept is extremely important. It makes your code extremely easy to read and understand.

- [x] revise

**Review by matkatmusic — APPROVED** [review]

**Pull request merged**
